pub mod find_the_differences;
pub mod majority_element_of_an_array;
pub mod merge_alt;
pub mod merge_sorted_array;
pub mod palindrome;
pub mod remove_an_element;
pub mod remove_duplicates_from_sorted_array_two;
pub mod remove_duplicates_sorted_array;
pub mod rotate_array;
